### ISSUE TITLE
[Feature Request]: Add a few plugins

### ISSUE THREAD

**Issue by sameersegal** [OpenNyAI/Jugalbandi-Studio-Engine#2]
### Is your feature request related to a problem? Please describe.

We need to have a few plugins that work with the Studio

### Describe the solution you'd like

1. Create relevant plugins
2. Update the Quickstart tutorial to use these plugins
    1. Serve the plugins
    2. Update the sql file to insert the plugins
    3. Serve the plugin descriptions using links from raw.github.com

**Comment by kanak8278** [comment]
#7 Plugins are added

2 Plugins are added: Knowledge Base and Reasoning
