### ISSUE TITLE
[Issue]:  NLR Formatting

### ISSUE THREAD

**Issue by kanak8278** [OpenNyAI/Jugalbandi-Studio-Engine#28]
### Describe the issue

* The NLR display could be improved by adding formatting.
* Highlight changes in the NLR.

**Comment by sm98** [comment]
Add numbering, indentation and change 'variables' to 'entries'

Example:

**Step 01: Greet user task**
\t	**Message:** _"Welcome to Pizza..."_
\t	**Description:**
 
**Step 02: Ask for pizza size task
\t	Message:
\t	Options:
\t	Condition:**

**Entries:
\t	Pizza Size:** should be small medium of large
