### ISSUE TITLE
[Feature Request]: NLR in Flow Chart

### ISSUE THREAD

**Issue by sameersegal** [OpenNyAI/Jugalbandi-Studio-Engine#4]
### Is your feature request related to a problem? Please describe.

We need to update the flow chart script for the new DSL.

### Describe the solution you'd like

Build on existing script https://github.com/OpenNyAI/Jugalbandi-Studio-Engine/blob/main/app/utils/vizgen.py

**Comment by kanak8278** [comment]
#6 Flow Chart Added.
